//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDbCoonection.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pproduct
    {
        public int PId { get; set; }
        public string Pname { get; set; }
        public Nullable<double> PPrice { get; set; }
        public Nullable<System.DateTime> PMfgDate { get; set; }
        public Nullable<System.DateTime> PExpDate { get; set; }
    }
}
